language: zsh
addons:
  apt:
    packages:
    - build-essential
before_install:
- mkdir $(pwd)/bin
- curl -L http://downloads.sourceforge.net/zsh/zsh-5.0.7.tar.gz | tar zx
- cd zsh-5.0.7
- ./configure --prefix=$(pwd)/bin
- make
- make install
- cd -
- export PATH="$(pwd)/bin:$PATH"
before_script:
- ls -al $(pwd)/bin
- zsh --version
script: make test
