language: zsh
addons:
  apt:
    packages:
    - build-essential
before_install:
- export BIN="$(pwd)/bin"
- mkdir $BIN
- curl -L http://downloads.sourceforge.net/zsh/zsh-5.0.7.tar.gz | tar zx
- cd zsh-5.0.7
- ./configure --prefix=$BIN
- make
- make install
- cd -
- export PATH="$BIN:$PATH"
before_script:
- ls -al $(pwd)/bin
- zsh --version
script: make test
